/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --config dist/server/wrangler.json worker-configuration.d.ts` (hash: ec3c39e65cb188306bd6876fdd69ba74)
interface __BaseEnv_Env {
	DB: D1Database;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
